baseurl = "http://blog.liul85.com"
languageCode = "en-US"
title = "liul85"
theme = "hemingway"
copyright = "&copy; theme by <a href=\"https://github.com/tanksuzuki\">Asuka Suzuki</a> 2016"
disqusShortname = "liul85"
googleAnalytics = ""

[params]

[params.highlight]
style = "github"
languages = ["go", "dockerfile", "javascript"]

[[params.social]]
url = "https://github.com/liul85"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/liul85"
fa_icon = "fa-twitter"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"
