baseurl = "http://liul85.me"
languageCode = "en"
title = "Liang Liu"
theme = "kiss"
copyright = "&copy; <a href=\"https://github.com/ribice\">Liul85 | theme by Emir Ribic</a> 2017"
disqusShortname = "liul85"
googleAnalytics = ""
Paginate = 5
enableRobotsTXT = true

[params.rss]
includeContent = true
authorName = "Ryan Liu"
authorEmail = "liul85@gmail.com"

[params.assets]
customCSS = ["css/custom.css"]

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = true # Adds OpenGraph and Twitter cards
homeTitle = "Liang Liu's blog" # Title for home page
poweredby = true # Adds powered by hugo and kiss below Copyright
related = true # Includes related articles at the bottom of the article

[params.social.config]
platforms = ["github","twitter","instagram","email","linkedin"]

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "liul85" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]
twitter = "liul85"
github = "liul85"
email = "liul85@gmail.com"
linkedin = "liang-liu-39543929"
instagram = "liul85"
rss = "index.xml"

[params.matomoAnalytics]
siteID = 1
rootURL = "//matomo.example.com/"

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true
